[
  'Tinkoff-WHR-Prod',
  'VTEX Payment',
  'Worldpay-WHR',
  'Worldpay-WHR-Prod',
  'itau-se-crediario',
  'vtex-integration-mollie-v0',
  'vtex-connector-paypal-commerce-platform-v0',
  'vtex-connector-instore-v0',
  'vtex-sequra-connector-v0',
  'softsuavepartnersg-payment-provider-protocol-ss-v0',
  'Pagodil-IT-Prod',
  'Klarna',
  'vtex-connector-adyen-v0',
]
